### ISSUE TITLE
Augment storage unit recipe to use any chest?

### ISSUE THREAD

**Issue by sykora** [bluemagic123/MagicStorage#3]
Just a quick feature request: would it be possible to allow any kind of chest to be used in the recipe for storage units?

**Comment by Jofairden** [comment]
Looking at the code ([#L31](https://github.com/bluemagic123/MagicStorage/blob/master/Items/StorageUnit.cs#L31) and [#L39](https://github.com/bluemagic123/MagicStorage/blob/master/Items/StorageUnit.cs#L39)) it seems to be adding `ItemID.Chest` as an ingredient, which iirc should cover all vanilla chest variants, this might be an oversight though.

**Comment by bluemagic123** [comment]
It was intentional that only the default chest can be used. I guess I can make it in the next update so that any wooden chest can be used though.

**Comment by Zsashas** [comment]
Why not just any chest?

**Comment by bluemagic123** [comment]
Mostly because it'll be hard to choose what chest gets chosen for crafting; imagine if someone makes Storage Units in the upcoming Crafting Interface then their hard-earned biome dungeon chest gets consumed.

**Comment by Zsashas** [comment]
I thought that recipes that used interchangeable items automatically grabbed the first one in the inventory? Like, the closest to the top-left. That's how it seems to work with wood stuff, anyway.

**Comment by bluemagic123** [comment]
Yes, but when you're looking at your storage items you don't know which item is first. I think I've thought of a solution though so I'll go ahead and make all chests usable (I think I also have a way to make even modded chests work).

**Comment by Zsashas** [comment]
I mean if it says just "Any Chest" it seems pretty straightforward, really.
