### ISSUE TITLE
when removing a crafting interface block, all crafting stations are lost

### ISSUE THREAD

**Issue by slippycheeze** [bluemagic123/MagicStorage#9]
Found in v0.4.  To reproduce:

1. Place an appropriately connected crafting interface.
2. Add a couple of crafting stations.  Doesn't matter which.
3. Use the pickaxe to break the block.

At this point you have one crafting interface block, and nothing more.  It just ate all those crafting stations, nom nom nom.

It would be ideal if, eg, this simply dropped all those crafting stations into the world at that point, essentially returning them to the user instead of destroying them.

**Comment by bluemagic123** [comment]
Fixed with 08bd95e591329ebeddd97fdb454a81f90b63bb1d
